---
title: "final_project_map"
output:
  html_document: default
  pdf_document: default
date: "2024-04-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)

ny_house_data <- read_csv("/Users/cyn_chen/Desktop/Group_C_NYCHouse/Data/NY-House-Dataset.csv")
```

```{r}
# For simplicity, remove rows with missing values
ny_house_data <- ny_house_data %>% na.omit()

# Convert relevant columns to numeric
ny_house_data$price <- as.numeric(ny_house_data$PRICE)
ny_house_data$beds <- as.numeric(ny_house_data$BEDS)
ny_house_data$bath <- as.numeric(ny_house_data$BATH)
ny_house_data$propertysqft <- as.numeric(ny_house_data$PROPERTYSQFT)

# Calculate the first quartile (Q1), third quartile (Q3), and IQR
Q1 <- quantile(ny_house_data$PRICE, 0.25)
Q3 <- quantile(ny_house_data$PRICE, 0.75)
IQR <- Q3 - Q1

# Define the lower and upper bounds for outliers
lower_bound <- Q1 - 1.5 * IQR
upper_bound <- Q3 + 1.5 * IQR

# Filter out rows with `PRICE` values outside of the bounds
ny_house_data <- ny_house_data %>%
  filter(PRICE >= lower_bound & PRICE <= upper_bound)
```

```{r}
#Extracting zip code from column STATE, then store in new column ZIP_CODE
library(stringr)
ny_house_data$ZIP_CODE <- str_extract(ny_house_data$STATE, "\\d{5}$")

#Add a new column, price per sqft
ny_house_data$PRICE_PER_SQFT<-ny_house_data$PRICE/ny_house_data$PROPERTYSQFT

# Group the data frame by ZIP_CODE and calculate the median price
median_prices_per_sqft <- ny_house_data %>%
  group_by(ZIP_CODE) %>%
  summarize(median_price = median(PRICE/PROPERTYSQFT, na.rm = TRUE))

median_prices_per_sqft$ZIP_CODE<-as.integer(median_prices_per_sqft$ZIP_CODE)
```

```{r}
#Import Zip Code Boundaries file for New York City
ny_zipcode_shape<-read.csv("/Users/cyn_chen/Desktop/Group_C_NYCHouse/Data/Modified_Zip_Code_Tabulation_Areas__MODZCTA_.csv")
zip_codes_with_prices <- left_join(ny_zipcode_shape,median_prices_per_sqft,by=c("MODZCTA"="ZIP_CODE"))

# Remove rows with missing values
zip_codes_with_prices <- zip_codes_with_prices[complete.cases(zip_codes_with_prices), ]

# Drop unnecessary columns by name
columns_to_drop <- c("label", "ZCTA","pop_est")
zip_codes_with_prices <- zip_codes_with_prices[, !(names(zip_codes_with_prices) %in% columns_to_drop)]

zip_codes_with_prices$MODZCTA<-as.numeric(zip_codes_with_prices$MODZCTA)
```


```{r}
ny_house_data_map<-data.frame(
  FORMATTED_ADDRESS=ny_house_data$FORMATTED_ADDRESS,
  TYPE=ny_house_data$TYPE,
  TOTAL_PRICE=ny_house_data$PRICE,
  PRICE_PER_SQFT=ny_house_data$PRICE_PER_SQFT,
  LONGITUDE=ny_house_data$LONGITUDE,
  LATITUDE=ny_house_data$LATITUDE
)
```

```{r}
library(leaflet)
# Create the Leaflet map
p1 <- leaflet(ny_house_data_map) %>%
  addTiles() %>%    
  addCircleMarkers(lng = ~ny_house_data_map$LONGITUDE, lat = ~ny_house_data_map$LATITUDE,
             popup = ~paste("<b>Address:</b>", ny_house_data$FORMATTED_ADDRESS,"<br>",
                            "<b>Establishment Type:</b> ", ny_house_data$TYPE,"<br>",
                            "<b>Price per sqft:</b> ",PRICE_PER_SQFT=ny_house_data$PRICE_PER_SQFT),
               clusterOptions = markerClusterOptions())
p1
```

```{r}
library(sf)
library(viridis)

# Convert the character strings to spatial objects
zip_codes_with_prices <- st_as_sf(zip_codes_with_prices, wkt = "the_geom")

# Create a color palette based on the average prices
pal <- colorNumeric(palette = "viridis", domain = zip_codes_with_prices$median_price)

# Create a leaflet map centered over a specific location 
p2 <- leaflet(data = zip_codes_with_prices) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~pal(median_price),  # Color by median_price
    fillOpacity = 0.7,
    color = "black",  # Border color
    weight = 1,  # Border thickness
    popup = ~paste("Zip Code:", MODZCTA, "<br>Median Price:", median_price),  # Add popup info
    highlight = TRUE  # Highlight on hover
  ) %>%
  addLegend(
    pal = pal,
    values = zip_codes_with_prices$median_price,
    title = "Median Price Per Sqft",
    position = "bottomright"  # Legend position
  )

p2
```

```{r}
ny_retail_data <- read.csv("/Users/cyn_chen/Desktop/Group_C_NYCHouse/Data/archive/retail-food-stores.csv")

# Convert relevant columns to numeric
ny_retail_data$Zip.Code <- as.numeric(ny_retail_data$Zip.Code)

#Select a subset of data interested 
ny_retail_data <- ny_retail_data %>%
  select(
    Name = DBA.Name,
    EstablishmentType = Establishment.Type,
    City = City,
    ZipCode = Zip.Code,
    Location = Location
  )

#Mutate the data to etract Latitude and Longtitude
ny_retail_data <- ny_retail_data %>%
  mutate(
    Latitude = as.numeric(str_extract(Location, "(?<='latitude': ')[^']+")) ,
    Longitude = as.numeric(str_extract(Location, "(?<='longitude': ')[^']+")),
    Location = NULL
  )

# For simplicity, remove rows with missing values
ny_retail_data <- ny_retail_data %>% na.omit()
```

```{r}
ny_zip_codes <- zip_codes_with_prices %>%
  select(ZipCode=MODZCTA)

ny_retail_data <- ny_retail_data%>%
  filter(ZipCode %in% ny_zip_codes$ZipCode)
```

```{r}
p3 <- leaflet(ny_retail_data) %>%
  addTiles() %>%    
  addCircleMarkers(lng = ~ny_retail_data$Longitude, lat = ~ny_retail_data$Latitude,
             popup = ~paste("<b>Name:</b>", ny_retail_data$Name,"<br>",
                            "<b>Establishment Type:</b> ", ny_retail_data$EstablishmentType,"<br>"),
               clusterOptions = markerClusterOptions())
p3
```

```{r}
establishments_by_zip <- ny_retail_data %>%
  group_by(ZipCode) %>%
  summarise(
    num_establishments = n_distinct(Name)
  )

zip_codes_with_num <- left_join(zip_codes_with_prices,establishments_by_zip,by=c("MODZCTA"="ZipCode"))

zip_codes_with_num <- zip_codes_with_num %>% na.omit()

str(zip_codes_with_num)
```

```{r}
# Convert the character strings to spatial objects
zip_codes_with_num <- st_as_sf(zip_codes_with_num, wkt = "the_geom")

# Create a color palette based on the average prices
pal2 <- colorNumeric(palette = "viridis", domain = zip_codes_with_num$num_establishments)

# Create a leaflet map centered over a specific location 
p4 <- leaflet(data = zip_codes_with_num) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~pal2(num_establishments),  # Color by median_price
    fillOpacity = 0.7,
    color = "black",  # Border color
    weight = 1,  # Border thickness
    popup = ~paste("Zip Code:", MODZCTA, "<br>Number of Retail Establishment:", num_establishments),  # Add popup info
    highlight = TRUE  # Highlight on hover
  ) %>%
  addLegend(
    pal = pal2,
    values = zip_codes_with_num$num_establishments,
    title = "Number of Retail Establishment",
    position = "bottomright"  
  )

p4
```

